### ISSUE TITLE
Why clearml agent worker ignores PYTHONPATH and  CLEARML_AGENT_EXTRA_PYTHON_PATH?

### ISSUE THREAD

**Issue by gzzv** [allegroai/clearml-agent#220]
I try to run remote clearml agent in k8s cluster. I have several python packages which are located in the different paths. This paths are specified in PYTHONPATH, but agent worker can't import this packages. 
I also tried to add path to the CLEARML_AGENT_EXTRA_PYTHON_PATH, but again nothing. Can anyone help me and give me some advice?

**Comment by jkhenning** [comment]
Hi @gzzv, 


How are you passing the PYTHONPATH and the other env var? Can you include logs for this failure?

**Comment by gzzv** [comment]
Hi @jkhenning!
- PYTHONPATH is defined in base docker image, CLEARML_AGENT_EXTRA_PYTHON_PATH - in values.yaml file (`basePodTemplate.env` field).
- I've tested my script just in docker container and it works, but doesn't work in clearml agent pod.
- Also I've tried to pass command like this: `python3 -c 'import example_lib as ex; print(ex)'` as `agent.extra_docker_shell_script` to `clearml.clearmlConfig` field in values.yaml and again it doesn't work

**Comment by gzzv** [comment]
My values.yaml:
```yaml
imageCredentials:
  enabled: true
  existingSecret: regcredcloud
clearml:
  existingAgentk8sglueSecret: agentk8sglue
agentk8sglue:
  apiServerUrlReference: "https://example.com/"
  fileServerUrlReference: "https://example.com/"
  webServerUrlReference: "https://example.com/"
  defaultContainerImage: test_image:0.0.1
  queue: Processing
basePodTemplate:
  env:
    - name: CLEARML_AGENT_SKIP_CONTAINER_APT
      value: 'true'
    - name: CLEARML_AGENT_NO_UPDATE
      value: '1'
    - name: CLEARML_AGENT_SKIP_PYTHON_ENV_INSTALL
      value: '1'
  tolerations:
    - key: "nvidia.com/gpu"
      operator: Exists
      effect: "NoSchedule"
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
```
