### ISSUE TITLE
cannot install a package

### ISSUE THREAD

**Issue by LanceKnight** [allegroai/clearml-agent#60]
Hello, 

I'm a new user. I'm trying to remotely run an experiment but I cannot get torch-scatter installed. The error msg says it's missing 'torch' module. However, 'torch' is in the installed packages list. Can someone help me?
![image](https://user-images.githubusercontent.com/5760199/115904305-4057a700-a42a-11eb-8000-9cd4b6b628f0.png)

![image](https://user-images.githubusercontent.com/5760199/115904377-51a0b380-a42a-11eb-8d23-0b0cc4cf33b9.png)

**Comment by bmartinn** [comment]
Hi @LanceKnight 
It seems `torch-scatter` requires `torch` in the setup process, which unfortunately pip cannot support by itself.
Not to worry, you can just specify to `clearml-agent` to install it after all the other packages.
Add [here](https://github.com/allegroai/clearml-agent/blob/8569c02b33efc9b33cfa3bb441e9563692251d1f/docs/clearml.conf#L79) the following:
```
post_packages: ["torch-scatter", ]
```

**Comment by LanceKnight** [comment]
Thanks @bmartinn !

**Comment by LanceKnight** [comment]
Hi, @bmartinn 

Thanks for the detailed follow-up. I'm wondering where I can find systematic tutorials/documentation on these? The [tutorial](https://allegro.ai/clearml/docs/) on the official website is quite high-level. Like I also want to know how to let remote execution to run the program in the same folder where I ran the program manually, instead of creating a venv environment. The example gave by the tutorial did so but it didn't tell me how.

**Comment by bmartinn** [comment]
We are working on a new improved version of the documentation that will includes such tutorials, it will also be hosted on github so it will be easier to PR to :)
Specifically to your question:
> remote execution to run the program in the same folder where I ran the program manually

The agent assumes it needs to reinstall the environment from scratch, there is currently no way to let it "know" you already have a working venv to use. There is kind of a hack that allows you to achieve it but only with conda (as conda env is a fully separated environment). Would that help? Also why not crteate the venv? this way you can guarantee the venv can be recreated on any machine, also not to mention we just introduced venv caching, so only the second time you are executing the code, it will use the cached venv instead of recreating from scratch)

**Comment by LanceKnight** [comment]
Hi, @bmartinn 

Thanks for the answer! I'm just worrying creating too many duplicates of the repo will consume a lot of space, especially for the datasets. Also, not all of my local changes have been synced with github. And finally, since I'm encountering this issue #62 , I kinda feel the venv behaves different than my local copy of codes so these are the reasons.

**Comment by aurelien-m** [comment]
Hello, unfortunately I'm not able to fix a similar issue :/

I have this in my `clearml.conf` file:
```yml
    package_manager: {
        # supported options: pip, conda, poetry
        type: pip,

        # specify pip version to use (examples "<20", "==19.3.1", "", empty string will install the latest version)
        # pip_version: "<20"

        # virtual environment inheres packages from system
        system_site_packages: false,
        # install with --upgrade
        force_upgrade: false,

        # additional artifact repositories to use when installing python packages
        # extra_index_url: ["https://allegroai.jfrog.io/clearml/api/pypi/public/simple"]
        extra_index_url: ["http://172.16.1.196:8333/delair-stack/prod"]

        # additional conda channels to use when installing with conda package manager
        # conda_channels: ["pytorch", "conda-forge", "defaults", ]
        # conda_full_env_update: false
        # conda_env_as_base_docker: false

        # set the priority packages to be installed before the rest of the required packages
        priority_packages: ["click", ]

        # set the optional priority packages to be installed before the rest of the required packages,
        # In case a package installation fails, the package will be ignored,
        # and the virtual environment process will continue
        priority_optional_packages: ["click", ]

        # set the post packages to be installed after all the rest of the required packages
        post_packages: ["click", ]

        # set the optional post packages to be installed after all the rest of the required packages,
        # In case a package installation fails, the package will be ignored,
        # and the virtual environment process will continue
        # post_optional_packages: []

        # set to True to support torch nightly build installation,
        # notice: torch nightly builds are ephemeral and are deleted from time to time
        torch_nightly: false,
    },
```

But I still get this error:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aurelien/.clearml/venvs-builds/3.8/task_repository/auto-train.git/autotrain/__main__.py", line 7, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

I'm launching my `clearml-agent` with `clearml-agent daemon --foreground`. Any ideas? Thanks!
